version: "3.8"
services:
  backend:
    image: backend
    build: ./backend/build-tools/
    container_name: backend
    networks:
      - mynetwork
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/app/src
    depends_on:
      - database
    env_file:
      - .env

  database:
    image: postgres
    container_name: database
    networks:
      - mynetwork
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - mynetwork
    depends_on:
      - database

volumes:
  db-data:

networks:
  mynetwork:
    driver: bridge
