# Generated by Django 4.2.15 on 2024-08-29 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tenant_contract_end_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
