# Generated by Django 4.2.15 on 2024-08-30 11:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_tenant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='last_payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
